### ISSUE TITLE
Continued issue with Wind and Rain guage

### ISSUE THREAD

**Issue by macjeff** [planetk/homebridge-netatmo#18]
Data seems fine which is the reason you closed the old one but still two issues

1. Apple Home App (beta) works on every home bridge device (even other then netatmo) except the wind and rain gauge.  If I choose either it says not supported but all the other netatmo features work.

2. Using a couple of non-apple home kit apps I have the same problem.  

In some they don't even show up (rain and wind)

My favorite one which HomeBridge actually recommends is MyTouchHome on the app store.
The wind and rain gauge show up and the data from the wind and rain gauge show up but no title like  (This is just an example.  If you send me an address I can send an actual screenshot or upload it somewhere)

N/A        2

N/A        6

N/A      12

Where the 2 is the current wind....the 6 is the gust....and the 12 is the max for the day.

Same kind of thing with rain gauge.   All n/a for titles.   But the data is there.

The other apps may be ignoring the devices because of the bad titles.

**Comment by planetk** [comment]
Hi Jeff,

sorry, but it took a while for me to get back on this.

About the first point (ios beta 10). It's known that ios 10 causes problems with custom cahracteristics not officially supported by apple (see: https://github.com/nfarina/homebridge/issues/662)

So there's few other things than waiting.

On the second point a did some changes on naming characteristics, put this would require you to stop homebridge, remove the accessories and persist folder in ~/.homebridge and reset homebridge data on your iPhone. But this might be to much effort, since you have a couple of devices to setup.

**Comment by macjeff** [comment]
I can do this over the weekend.  

I really only have 1 iOS device.  The second shares the home kit data.  But I have a LOT of home kit devices mainly because I have every switch in my home automated.  I have to have home kit ignore some of the switches because there is a 100 device limit in home kit!!!!

So on the iOS 10 beta 4 device which is the main one do I just delete the home to reset the data and then add the home again?   And that is after I reset home bridge.    

I guess this means setting up all the rooms again but I can do that if I have to.  With about 100 devices it takes a while

Jeff
