### ISSUE TITLE
latest version not working anymore

### ISSUE THREAD

**Issue by JotWee** [planetk/homebridge-netatmo#20]
The latest version as per August,6 2016 is not working anymore. There are no services shown in the accessories

**Comment by planetk** [comment]
Hi,

thanx for your comment. It is a little difficult to give support, since everything works fine here. Could you please provide some more info?

I.e.:
- What app on what ios device are you using?
- What operating system are you running on?
- What netatmo devices are you using?
- whats the content of your config file? (leaving out credentials for privacy reasons)
- Did you already try to delete the accessories and persit folder in the ~/.homedrige folder?
- Did you already try to reset your homekit settings on iOS?
- What is the output on the console at startup and/or hombridge.log file?

Pleas provide any info that might be helpful to give some more support.

**Comment by JotWee** [comment]
It's completely independent of any iOS version or devices, independent from HomeKit app.
The config file is straight forward, I made no changes in months, so no reason there.
I deleted accessories and persist folder -> no effect
I will definitely not reset my advanced HomeKit setting as everything (including all other Homebridge platforms and devices) is working fine.
Log does not show anything special. I just get the accessory information service of the weather station interior and exterior module and no further services. I don't have wind or rain sensors attached.
It worked with the update before, just your update two days ago is not working for me.

**Comment by planetk** [comment]
Hi,

I rechecked all code chages from the 5. They only refelct comments and libs related to the welcome support, which does, as far as I can see from the little info you've given, not effect your settings.

Unfortunately I will not be able to give any support if I don't get more Info.
Maybe you should stick with an older version, since newest changes do not have any impact to your setting.
