### ISSUE TITLE
Thermostat & Rain Sensor show up as "not supported"

### ISSUE THREAD

**Issue by Crady123** [planetk/homebridge-netatmo#25]
Hi,

thank you for the fast fix adressing the "not supportes" issue for all Netatmo devices.

Now  I have the problem that my Thermostat (I really really really would use it with HomeKit) and the Rain Sensor are showing up as not supportet.

Also could you please give me a hint where to add the device types in to the homebridge cfg?
sorry.. I am very new to homebridge / linux / raspberry / ssh...

Thank you!

**Comment by planetk** [comment]
Hi,

no worries. I'll try to help you.

The problem is, that the rain gauge and the thermostat use their own service uuids and characteristic uuids.

Apple has a List of officially supported uuids, e.g. for Temperature sensor, etc. 
Since iOS 10 apple seems to be very picky about what accessories it accepts.
Looks like they want to sell there MFI certificates ...

In iOS 9 I have best results using the elgato eve app. Currently there is not much I can do on this issue. Maybe I'll find some time to map the thermostat to the original homekit thermostat service which is a little limited.

about the device type config:

just modify your config.json like following:

"platforms": [
        {
            "platform": "netatmo",
            "name": "netatmo platform",
            "ttl": 5,
             **"deviceTypes": [
             "weatherstation",
              "thermostat",
              "welcome"
            ], **
            "auth": {
                "client_id": "XXXXX Create at https://dev.netatmo.com/",
                "client_secret": "XXXXX Create at https://dev.netatmo.com/",
                "username": "your netatmo username",
                "password": "your netatmo password"
            }
        }
    ],

bold stuff is new.

The only thing you get on top is a very basic (call it alpha state) support for the welcome device.
So possibly this might not be helpful for you at all.

Kind regards
Stefan

**Comment by Crady123** [comment]
Thanks, that helped!

**Comment by danpoltawski** [comment]
Not completely following this issue, but wondering, can somehting be borrowed from https://github.com/KraigM/homebridge-nest to help address this?

**Comment by bozzomasterflash** [comment]
Hi, 
Thank you for this awesome plugin but I still have problems with rain sensor... that is showing off as not supported... 
thank you for your help

**Comment by planetk** [comment]
Hi,

there is a dev branch supporting thermostat:
https://github.com/planetk/homebridge-netatmo/tree/dev

It is not  really tested. But it also supports notifications.

Rain and wind are not supported by apple, sorry there is nothing I can do about that. You might want to use elgato eve instead.

**Comment by BuckarooToo** [comment]
Crady123 - just curious - did you get your rain gauge to work with homebridge? I'm trying to get my water to shutoff once 1 inch of rain (or in my case, irrigation) has fallen.
