### ISSUE TITLE
Outdoor module has status "no response" when using homebridge-netatmo from "dev" branch

### ISSUE THREAD

**Issue by savealive** [planetk/homebridge-netatmo#39]
Hi, just updated plugin from dev branch. Everything looks pretty good including thermostat and even CO2 push notifications for homekit triggers except the data from weather station outdoor module. It's having "no response" status in both Home and Eve apps. 

Screenshots:
![image](https://cloud.githubusercontent.com/assets/12967071/22333643/d44f1db8-e3df-11e6-81d8-9ebc73150ded.png)
![image](https://cloud.githubusercontent.com/assets/12967071/22333649/e3296f6e-e3df-11e6-9520-ac9211a5962a.png)

**Comment by savealive** [comment]
Update: it works normally when outdoor temperature is >= 0. 
Must be some type error in code.

**Comment by planetk** [comment]
Hi,

thanx a lot for your input. The hint with negative temperatures is very helpful.

Apple only allows positive value for Temperature. Maybe it is not that freezy in California.

In the "master" Branch I modified the lowest allowed temperature to a negative value.

Since I wanted to add better support for the home app, I left this out in the current dev branch.
When I change this, the module shows up as not supported in the home app.

I'll try to do a fix like follows:
- Add a mode which is not home compatible, but works with elgato eve
- In the home mode the temperature will be 0°C then for negative temperatures.

Thanx again for your support!

Kind regards
Stefan

**Comment by savealive** [comment]
Hi Stephan, 
That's strange, because it works as expected in older homebridge-netatmo plugin version. Negative temparatures displayed correctly in both iOS Home and Eve apps. 
I can switch to older plugin version (the one from npm repo) and provide a proof. I'm not sure we're talking about the same thing, but seems HomeKit API suppports temperatures <0.

**Comment by savealive** [comment]
Hi,
Just rolled back to previous plugin version. Please find Home App screenshots attached:

![image](https://cloud.githubusercontent.com/assets/12967071/22398084/af452d78-e588-11e6-94ee-83190b6f88bd.png)
![image](https://cloud.githubusercontent.com/assets/12967071/22398087/b703d24e-e588-11e6-8cf8-c12c8b4601da.png)

**Comment by planetk** [comment]
Hi,

I just did check in a patch in the dev branch. Can't test right now, but should work ...

**Comment by savealive** [comment]
Hi,
Yes, issue is now resolved, thanks!

**Comment by savealive** [comment]
![image](https://cloud.githubusercontent.com/assets/12967071/22398645/8e4a0550-e595-11e6-8954-764e5b73d8f8.png)
