### ISSUE TITLE
rain sensor problem

### ISSUE THREAD

**Issue by fildy** [planetk/homebridge-netatmo#5]
my rain sensor in homkit only show loading of the battery level. not the rain level. how to fix it?

**Comment by planetk** [comment]
Hi,

sorry for the late reply, quite busy days ...
Could you provide some more data? For eaxample the result of an API call?

**Comment by fildy** [comment]
Hi, no problem.
How I can get the result of API call?
Sorry, but I'm not programmer

**Comment by gismo141** [comment]
I have the exact same problem - how could I provide the needed information?

**Comment by planetk** [comment]
Hi everybody,

sorry for giving no response for that long time. This one is a little hard to find.

Possibly the issue is in the client you use. Sometimes some values are hidden.

I'm using Elgato Eve. In settings -> Typen (in german, might be types or characteristics) -> Theres a list of visible characteristics and of some hidden characteristics.

I hope the helps.

Kind regards

**Comment by planetk** [comment]
Considering this as solved. Please reopen if not.

**Comment by PeteLawrence** [comment]
I have the same problem, I believe the issue is due to the fact there is no 'battery_percent' key in the API response.
```
batteryLevel: function (callback) {
    this.getData(function (deviceData) {
      callback(null, deviceData.battery_percent);
    }.bind(this));
  },
```
